<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TrueCarField extends Model
{
    protected $fillable = [
        'internet_shop_id',
        'field_leader_name',
        'date_time_followup',
        'recommendation_email',
        'recommendation_call',
        'recommendation_sms',
        'general_note',
        'shop_type',
        'bs_honor_payments_tcdc',
        'bs_send_picvid',
        'bs_mention_ts_voicemail',
        'bs_mention_ts_email',
        'bs_mention_ts_text',
        'bs_mention_ts_video',
        'bs_attempt_appointment',
        'bs_home_delivery_offer',
        'to_meet_char_limits',
        'ab_provide_payment',
        'ab_honor_offer_tcdc',
        'ab_manual_discount_offer',
        'ab_script_what_payment',
        'ab_script_real_payment',
        'military_identify_rank',
        'military_thank_customer',
        'military_benefits_explained',
        'military_script_benefits',
        'pf_honor_nf_policy',
        'pf_contingencies',
        'pf_contingencies_if_yes',
        'pf_buyers_bonus',
        'pf_manual_discount_offer',
        'pf_script_approved_loan',
        'amex_allowed_amex',
        'amex_mention_bonus',
        'amex_manual_discount_offer',
        'amex_script_use_amex',
        'amex_script_limit',
        'sc_unprompted_bonus',
        'sc_bridge_rel_gap',
        'sc_partners',
        'sc_manual_discount_offer',
        'sc_didnt_know_answer',
        'sc_script_costco',
        'sc_script_pandora',
        'sc_script_what_payment',
        'cr_comments',
        'cr_bridge_rel_gap',
        'cr_appointment_attempt',
        'cr_home_delivery',
        'cr_partners',
        'cr_manual_discount_offer',
        'cr_didnt_know_answer',
        'cr_script_my_products_web',
        'cr_script_what_payment',
    ];

    protected $casts = [
        'bs_honor_payments_tcdc' => 'boolean',
        'bs_send_picvid' => 'boolean',
        'bs_mention_ts_voicemail' => 'boolean',
        'bs_mention_ts_email' => 'boolean',
        'bs_mention_ts_text' => 'boolean',
        'bs_mention_ts_video' => 'boolean',
        'bs_attempt_appointment' => 'boolean',
        'bs_home_delivery_offer' => 'boolean',
        'to_meet_char_limits' => 'boolean',
        'ab_provide_payment' => 'boolean',
        'ab_honor_offer_tcdc' => 'boolean',
        'ab_manual_discount_offer' => 'boolean',
        'military_identify_rank' => 'boolean',
        'military_thank_customer' => 'boolean',
        'military_benefits_explained' => 'boolean',
        'pf_honor_nf_policy' => 'boolean',
        'pf_contingencies' => 'boolean',
        'pf_contingencies_if_yes' => 'boolean',
        'pf_buyers_bonus' => 'boolean',
        'pf_manual_discount_offer' => 'boolean',
        'amex_allowed_amex' => 'boolean',
        'amex_mention_bonus' => 'boolean',
        'amex_manual_discount_offer' => 'boolean',
        'sc_unprompted_bonus' => 'boolean',
        'sc_bridge_rel_gap' => 'boolean',
        'sc_partners' => 'boolean',
        'sc_manual_discount_offer' => 'boolean',
        'sc_didnt_know_answer' => 'boolean',
        'cr_comments' => 'boolean',
        'cr_bridge_rel_gap' => 'boolean',
        'cr_appointment_attempt' => 'boolean',
        'cr_home_delivery' => 'boolean',
        'cr_partners' => 'boolean',
        'cr_manual_discount_offer' => 'boolean',
        'cr_didnt_know_answer' => 'boolean',
    ];

    public function internetShop()
    {
        return $this->belongsTo(InternetShop::class);
    }
}
